name: Publish to Packagist
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Notify Packagist
        uses: devdrjohndoe/packagist-update@v1
        with:
          username: ${{ secrets.amazing79}}
          token: ${{ secrets.63c0f069669ea686ca1dc001b32651dbd7b00278 }}
          package: "amazing79/middleware-stack"
